Shapes

In [ ]:
a=np.array([1,2,3,4])
print("a:",a)
print("shape:",a.shape)
print("dimension:",a.ndim)


a: [1 2 3 4]
shape: (4,)
dimension: 1


In [ ]:
row = np.array([1, 2, 3])
mat = np.array([[10, 20, 30], [40, 50, 60]])

print("row + 100:", row + 100)
print("mat / 10:\n", mat / 10)


row + 100: [101 102 103]
mat / 10:
 [[1. 2. 3.]
 [4. 5. 6.]]


In [6]:
# --- 1D (length n) + 2D (m, n): align from the right; the vector runs along the last axis ---
# Shape (3,) vs (2, 3) -> left-pad (3,) to (1, 3); stretch axis 0 from 1 to 2
vec = np.array([1, 0, -1])
grid = np.array([[1, 2, 3], [4, 5, 6]])

print("vec:", vec, "-> effective (1, 3) then broadcast to (2, 3)")
print("grid + vec:\n", grid + vec)

vec: [ 1  0 -1] -> effective (1, 3) then broadcast to (2, 3)
grid + vec:
 [[2 2 2]
 [5 5 5]]


In [7]:
# --- Column vector (n, 1) + row (1, m) -> outer-style (n, m) grid ---
# (3, 1) + (1, 4) both broadcast: 1 stretches to match the other side
col = np.array([[0], [10], [20]])  # shape (3, 1)
row = np.array([[0, 1, 2, 3]])   # shape (1, 4)

print("col + row (coordinate grids):\n", col + row)

col + row (coordinate grids):
 [[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]]


In [10]:
# --- Incompatible shapes: (3,) and (4,) cannot broadcast (last dims 3 vs 4, neither is 1) ---
try:
    np.arange(3) + np.arange(4)
except ValueError as e:
    print("Expected error:", e)

Expected error: operands could not be broadcast together with shapes (3,) (4,) 


In [11]:
# --- Inspecting broadcast results without computing the full ufunc ---
# broadcast_arrays expands inputs to a common shape (may share memory for size-1 axes)
x = np.array([1, 2, 3])
y = np.array([[0], [10]])  # (2, 1)

xb, yb = np.broadcast_arrays(x, y)
print("x broadcast shape:", xb.shape)
print("xb:\n", xb)
print("yb:\n", yb)

x broadcast shape: (2, 3)
xb:
 [[1 2 3]
 [1 2 3]]
yb:
 [[ 0  0  0]
 [10 10 10]]


In [12]:
# --- Boolean indexing / comparisons also use broadcasting ---
# Compare a column to each row value in one expression
data = np.array([[1, 2, 3], [4, 5, 6]])
thresholds = np.array([[2], [5]])  # (2, 1)

mask = data > thresholds  # (2,3) vs (2,1) -> (2,3) boolean array
print("mask:\n", mask)

mask:
 [[False False  True]
 [False False  True]]
